// CRUIZR - Production Dataset (City-aware fleet, Campus hubs, FAQs, Reviews, & Roadtrips)

const APP_DATA = {
  brand: {
    name: "CRUIZR",
    tagline: "Rent. Ride. Roadtrip.",
    subtext: "Pocket-friendly self-drive cars for college students, campus runs & epic road trips."
  },
  
  campusHubs: [
    { id: "blr-christ", city: "Bangalore", name: "Christ University & Koramangala Hub", shortName: "Christ Univ", priceMultiplier: 1.0, count: 8, icon: "graduation-cap" },
    { id: "blr-pes", city: "Bangalore", name: "PES Univ & Electronic City Hub", shortName: "PES Univ", priceMultiplier: 1.03, count: 6, icon: "graduation-cap" },
    { id: "del-north", city: "Delhi NCR", name: "Delhi University North Campus", shortName: "DU North", priceMultiplier: 0.95, count: 8, icon: "graduation-cap" },
    { id: "del-south", city: "Delhi NCR", name: "Hauz Khas & South Campus Hub", shortName: "Hauz Khas", priceMultiplier: 1.05, count: 7, icon: "graduation-cap" },
    { id: "del-noida", city: "Delhi NCR", name: "Amity Noida & Knowledge Park", shortName: "Amity Noida", priceMultiplier: 0.98, count: 6, icon: "graduation-cap" },
    { id: "pune-symbiosis", city: "Pune", name: "Symbiosis Viman Nagar Hub", shortName: "Symbiosis", priceMultiplier: 1.02, count: 8, icon: "graduation-cap" },
    { id: "pune-fc", city: "Pune", name: "FC Road & MIT Kothrud Hub", shortName: "FC Road", priceMultiplier: 0.96, count: 6, icon: "graduation-cap" },
    { id: "mum-bandra", city: "Mumbai", name: "Bandra & Mithibai / NMIMS Hub", shortName: "Bandra", priceMultiplier: 1.15, count: 7, icon: "graduation-cap" },
    { id: "mum-powai", city: "Mumbai", name: "IIT Bombay & Powai Hub", shortName: "IIT Powai", priceMultiplier: 1.10, count: 6, icon: "graduation-cap" },
    { id: "chn-vit", city: "Chennai / Vellore", name: "VIT & OMR Tech Corridor", shortName: "VIT Chennai", priceMultiplier: 0.92, count: 6, icon: "graduation-cap" },
    { id: "manipal", city: "Manipal", name: "Manipal University Campus Hub", shortName: "Manipal Univ", priceMultiplier: 0.94, count: 6, icon: "graduation-cap" },
    { id: "goa-bits", city: "Goa", name: "BITS Goa & Panjim Coastal Hub", shortName: "BITS Goa", priceMultiplier: 1.20, count: 8, icon: "palmtree" },
    { id: "hyd-gachibowli", city: "Hyderabad", name: "IIIT / Gachibowli Univ Hub", shortName: "IIIT Gachibowli", priceMultiplier: 1.04, count: 6, icon: "graduation-cap" }
  ],

  promoCodes: [
    {
      code: "STUDENT25",
      discount: 25,
      type: "percent",
      maxDiscount: 1500,
      title: "🎓 Student Special",
      desc: "Flat 25% OFF for college students with valid student ID / .edu email",
      tag: "POPULAR"
    },
    {
      code: "NIGHTOWL",
      discount: 400,
      type: "flat",
      minAmount: 1200,
      title: "🌙 Midnight Food Run",
      desc: "Flat ₹400 OFF for late-night drives (8 PM - 6 AM)",
      tag: "NIGHT PACK"
    },
    {
      code: "ROADTRIP",
      discount: 30,
      type: "percent",
      maxDiscount: 3500,
      title: "🏖️ Weekend Getaway",
      desc: "30% OFF on bookings of 2 days or more (Goa, Hills, Beaches)",
      tag: "WEEKEND"
    },
    {
      code: "FIRSTCRUIZE",
      discount: 500,
      type: "flat",
      minAmount: 1500,
      title: "⚡ Freshers Special",
      desc: "₹500 OFF on your first CRUIZR self-drive experience",
      tag: "NEW USER"
    }
  ],

  cars: [
    // ---------------- BANGALORE ----------------
    {
      id: "car-swift",
      name: "Maruti Suzuki Swift",
      year: 2024,
      city: "Bangalore",
      hubId: "blr-christ",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Manual",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 99,
      pricePerDay: 1399,
      rating: 4.86,
      tripsCount: 420,
      image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
      features: ["Apple CarPlay / Android Auto", "Bluetooth Stereo", "Fastag Enabled", "Super Fuel Efficient 22 km/l"],
      location: "Christ Univ Gate 2 • 0.4 km away",
      zeroDeposit: true,
      badge: "Campus Favorite 🔥",
      quickBubble: "⚡ 22 km/l • Apple CarPlay • Free FASTag",
      specs: { mileage: "22.5 km/l", boot: "268 Litres", speed: "165 km/h", sound: "6-Speaker Stereo + Aux" },
      desc: "The ultimate college daily driver. Super light on the pocket, smooth in city traffic, and roomy enough for the entire study group."
    },
    {
      id: "car-thar",
      name: "Mahindra Thar 4x4 Hard-Top",
      year: 2024,
      city: "Bangalore",
      hubId: "blr-christ",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 4,
      pricePerHour: 220,
      pricePerDay: 3199,
      rating: 4.95,
      tripsCount: 380,
      image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
      features: ["Convertible / Rugged 4x4", "High Ground Clearance", "Touchscreen Audio", "Hill Assist"],
      location: "Koramangala 4th Block • 1.2 km away",
      zeroDeposit: true,
      badge: "Epic Roadtrip ⛰️",
      quickBubble: "⛰️ 4x4 Offroad • 226mm Clearance • M-Hawk Power",
      specs: { mileage: "14.2 km/l", boot: "Adventure Luggage Space", speed: "155 km/h", sound: "Roof-Mounted Adventure Sound" },
      desc: "The undisputed king of weekend road trips. Unmatched road presence, rugged off-road vibes, and built for mountain getaways."
    },
    {
      id: "car-creta-blr",
      name: "Hyundai Creta SX Turbo",
      year: 2024,
      city: "Bangalore",
      hubId: "blr-christ",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 200,
      pricePerDay: 2899,
      rating: 4.92,
      tripsCount: 290,
      image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
      features: ["Panoramic Sunroof", "Paddle Shifters", "Bose Premium Audio", "Ventilated Seats"],
      location: "Christ Univ Central Block • 0.3 km away",
      zeroDeposit: true,
      badge: "Sunroof Turbo ✨",
      quickBubble: "✨ Panoramic Sunroof • Turbo Petrol • Bose Sound",
      specs: { mileage: "17.4 km/l", boot: "433 Litres", speed: "185 km/h", sound: "Bose 8-Speaker Studio" },
      desc: "Smooth turbo-petrol automatic with a wide panoramic sunroof. The top choice for comfortable cruising and squad weekend getaways."
    },
    {
      id: "car-virtus",
      name: "Volkswagen Virtus GT",
      year: 2024,
      city: "Bangalore",
      hubId: "blr-christ",
      category: "sedan",
      categoryName: "Vibe Sedan",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 180,
      pricePerDay: 2599,
      rating: 4.93,
      tripsCount: 340,
      image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
      features: ["German Engineering", "Paddle Shifters", "5-Star Global NCAP Safety", "Digital Cockpit"],
      location: "Indiranagar 100ft Rd • 1.5 km away",
      zeroDeposit: true,
      badge: "German Vibe 🏎️",
      quickBubble: "🏎️ 150 BHP Turbo • Paddle Shifters • 5-Star NCAP",
      specs: { mileage: "18.1 km/l", boot: "521 Litres (Gigantic)", speed: "205 km/h", sound: "Digital Cockpit Audio" },
      desc: "Built for true driving enthusiasts. High-speed highway stability, sporty red accents, and 5-star crash safety for absolute peace of mind."
    },
    {
      id: "car-scorpio-blr",
      name: "Mahindra Scorpio-N (7 Seater)",
      year: 2024,
      city: "Bangalore",
      hubId: "blr-pes",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 7,
      pricePerHour: 245,
      pricePerDay: 3499,
      rating: 4.94,
      tripsCount: 310,
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      features: ["7 Full-size Seats", "mStallion Turbo Petrol", "Dual Zone AC", "Sony 3D Sound"],
      location: "PES Univ Electronic City • 0.5 km away",
      zeroDeposit: true,
      badge: "Big Squad 7-Seater 👥",
      quickBubble: "👥 7 Full Seats • 200 BHP Turbo • Sony 3D Sound",
      specs: { mileage: "13.5 km/l", boot: "7-Seater Modular Boot", speed: "180 km/h", sound: "Sony 12-Speaker 3D Immersive" },
      desc: "Got the whole batch or society wing traveling together? 7 seats, monster road stance, and crazy 3D surround sound for sing-along road trips."
    },
    {
      id: "car-verna-blr",
      name: "Hyundai Verna SX CRDi",
      year: 2024,
      city: "Bangalore",
      hubId: "blr-christ",
      category: "sedan",
      categoryName: "Vibe Sedan",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 5,
      pricePerHour: 170,
      pricePerDay: 2399,
      rating: 4.88,
      tripsCount: 220,
      image: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
      features: ["High Mileage Diesel", "Heated/Cooled Seats", "Fastag Enabled", "Sporty Cockpit"],
      location: "Koramangala 5th Block • 0.8 km away",
      zeroDeposit: true,
      badge: "Diesel Cruiser ⛽",
      quickBubble: "⛽ 24 km/l Diesel • Super Highway Mileage • Sporty",
      specs: { mileage: "24.0 km/l", boot: "528 Litres", speed: "195 km/h", sound: "Bose Surround" },
      desc: "Ultra-long range diesel cruiser. Spend minimal cash on fuel and maximize road trip vibes all the way to Mysore or Coorg."
    },
    {
      id: "car-nexon-blr",
      name: "Tata Nexon EV Max",
      year: 2024,
      city: "Bangalore",
      hubId: "blr-christ",
      category: "ev",
      categoryName: "Electric EV",
      transmission: "Automatic",
      fuel: "Electric",
      seats: 5,
      pricePerHour: 140,
      pricePerDay: 1999,
      rating: 4.89,
      tripsCount: 260,
      image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
      features: ["453 km Range", "Fast Charging 0-80% in 50m", "Zero Fuel Expense", "Silent Cabin & Instant Torque"],
      location: "Christ Univ Gate 1 • 0.2 km away",
      zeroDeposit: true,
      badge: "Zero Fuel Cost 🔋",
      quickBubble: "🔋 453km Electric Range • ₹0 Fuel • Instant Torque",
      specs: { mileage: "453 km / Full Charge", boot: "350 Litres", speed: "140 km/h", sound: "Harman 8-Speaker Studio" },
      desc: "Save 100% on petrol! Cruise silently with electric torque and complimentary fast charging at 5,000+ public charging stations."
    },
    {
      id: "car-bmw-blr",
      name: "BMW 330i M-Sport",
      year: 2023,
      city: "Bangalore",
      hubId: "blr-christ",
      category: "luxury",
      categoryName: "Flex / Luxury",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 450,
      pricePerDay: 6499,
      rating: 4.98,
      tripsCount: 165,
      image: "https://images.unsplash.com/photo-1555353540-64580b51c258?auto=format&fit=crop&w=800&q=80",
      features: ["258 BHP Twin-Turbo", "Harman Kardon Surround", "M-Sport Body Styling", "Heads-Up Display"],
      location: "Koramangala Sony World • 1.1 km away",
      zeroDeposit: false,
      badge: "Graduation Flex 👑",
      quickBubble: "👑 258 BHP Twin-Turbo • Harman Kardon • M-Sport",
      specs: { mileage: "13.8 km/l", boot: "480 Litres", speed: "250 km/h", sound: "Harman Kardon 16-Speaker" },
      desc: "Turn every head on campus. The ultimate luxury flex for college fest arrivals, graduation galas, birthday night outs, and premium dates."
    },

    // ---------------- DELHI NCR ----------------
    {
      id: "car-i20",
      name: "Hyundai i20 Sportz",
      year: 2023,
      city: "Delhi NCR",
      hubId: "del-north",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 115,
      pricePerDay: 1699,
      rating: 4.82,
      tripsCount: 295,
      image: "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=800&q=80",
      features: ["Smooth Automatic", "Wireless Phone Charger", "Bose 6-Speaker System", "Rear AC Vents"],
      location: "North Campus Metro Hub • 0.6 km away",
      zeroDeposit: true,
      badge: "Smooth Auto ⚡",
      quickBubble: "🎵 Bose Audio • Wireless Charger • Smooth CVT",
      specs: { mileage: "19.8 km/l", boot: "311 Litres", speed: "170 km/h", sound: "Bose Premium 7-Speaker" },
      desc: "Chic styling with crisp audio setup. Perfect for stress-free automatic cruising during rush hours and city coffee runs."
    },
    {
      id: "car-swift-del",
      name: "Maruti Suzuki Swift",
      year: 2024,
      city: "Delhi NCR",
      hubId: "del-north",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Manual",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 95,
      pricePerDay: 1349,
      rating: 4.85,
      tripsCount: 310,
      image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
      features: ["Manual Fun", "Fastag", "Bluetooth", "22 km/l Mileage"],
      location: "DU North Campus Vishwavidyalaya • 0.3 km away",
      zeroDeposit: true,
      badge: "Pocket Friendly 💸",
      quickBubble: "💸 ₹1,349/day • 22 km/l • North Campus Ready",
      specs: { mileage: "22.5 km/l", boot: "268 Litres", speed: "165 km/h", sound: "Stereo with Aux" },
      desc: "The student classic for Murthal paratha runs at 2 AM. Reliable, punchy manual gearbox and dirt-cheap fuel spend."
    },
    {
      id: "car-scorpio-n",
      name: "Mahindra Scorpio-N (7 Seater)",
      year: 2024,
      city: "Delhi NCR",
      hubId: "del-south",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 7,
      pricePerHour: 240,
      pricePerDay: 3499,
      rating: 4.94,
      tripsCount: 460,
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      features: ["7 Full-size Seats", "Sony 12-Speaker 3D Audio", "Massive Power 175 BHP", "Dual Zone AC"],
      location: "Hauz Khas Village • 1.1 km away",
      zeroDeposit: true,
      badge: "Big Squad 7-Seater 👥",
      quickBubble: "👥 7 Full Seats • Sony 3D Sound • 175 BHP Beast",
      specs: { mileage: "15.0 km/l", boot: "7-Seater Modular Boot", speed: "175 km/h", sound: "Sony 12-Speaker 3D Immersive" },
      desc: "Got the whole batch or society friends traveling together? 7 seats, monster road stance, and crazy 3D surround sound for sing-along road trips."
    },
    {
      id: "car-thar-del",
      name: "Mahindra Thar 4x4 Petrol AT",
      year: 2024,
      city: "Delhi NCR",
      hubId: "del-south",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 4,
      pricePerHour: 230,
      pricePerDay: 3299,
      rating: 4.96,
      tripsCount: 350,
      image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
      features: ["4x4 Automatic", "Convertible Top", "Touchscreen", "Hill Hold Assist"],
      location: "Hauz Khas Social Gate • 0.5 km away",
      zeroDeposit: true,
      badge: "Squad 4x4 ⛰️",
      quickBubble: "⛰️ 150 BHP Turbo Petrol Auto • 4x4 Offroad",
      specs: { mileage: "13.5 km/l", boot: "Adventure Boot", speed: "160 km/h", sound: "Roof Adventure Sound" },
      desc: "Smooth petrol automatic Thar ready for Rishikesh river rafting trips and scenic mountain passes."
    },
    {
      id: "car-city-del",
      name: "Honda City i-DTEC Diesel",
      year: 2023,
      city: "Delhi NCR",
      hubId: "del-noida",
      category: "sedan",
      categoryName: "Vibe Sedan",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 5,
      pricePerHour: 165,
      pricePerDay: 2399,
      rating: 4.87,
      tripsCount: 280,
      image: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
      features: ["Legendary i-DTEC Diesel", "Sunroof", "Cruise Control", "Super 25 km/l Mileage"],
      location: "Amity Gate 2 Noida • 0.4 km away",
      zeroDeposit: true,
      badge: "Expressway King 🚗",
      quickBubble: "🚗 25.6 km/l • Cruise Control • Sunroof",
      specs: { mileage: "25.6 km/l", boot: "506 Litres", speed: "190 km/h", sound: "8-Speaker Surround" },
      desc: "King of the Yamuna Expressway. Incredibly efficient diesel motor makes Agra and Jaipur drives practically cost-free."
    },

    // ---------------- PUNE ----------------
    {
      id: "car-creta",
      name: "Hyundai Creta SX (Sunroof)",
      year: 2024,
      city: "Pune",
      hubId: "pune-symbiosis",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Diesel",
      seats: 5,
      pricePerHour: 195,
      pricePerDay: 2799,
      rating: 4.91,
      tripsCount: 512,
      image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
      features: ["Panoramic Sunroof", "Ventilated Seats", "Cruise Control", "Large 433L Boot"],
      location: "Symbiosis Viman Nagar • 0.8 km away",
      zeroDeposit: true,
      badge: "Panoramic Sunroof ✨",
      quickBubble: "✨ Panoramic Sunroof • Cruise Control • 433L Boot",
      specs: { mileage: "18.5 km/l", boot: "433 Litres (Squad Bags)", speed: "180 km/h", sound: "Surround Acoustic Sound" },
      desc: "Spacious luxury SUV loaded with a huge panoramic sunroof and punchy diesel engine. The top pick for Goa and hill station trips."
    },
    {
      id: "car-swift-pune",
      name: "Maruti Suzuki Swift",
      year: 2024,
      city: "Pune",
      hubId: "pune-fc",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Manual",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 99,
      pricePerDay: 1399,
      rating: 4.88,
      tripsCount: 340,
      image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
      features: ["Apple CarPlay", "Bluetooth Stereo", "22 km/l Mileage", "FASTag"],
      location: "FC Road Goodluck Cafe • 0.2 km away",
      zeroDeposit: true,
      badge: "Campus Favorite 🔥",
      quickBubble: "🔥 ₹1,399/day • 22 km/l • FC Road Hub",
      specs: { mileage: "22.5 km/l", boot: "268 Litres", speed: "165 km/h", sound: "6-Speaker Audio" },
      desc: "Lonavala sunrise drives made ultra affordable. Zip through western ghat roads with friends."
    },
    {
      id: "car-thar-pune",
      name: "Mahindra Thar 4x4",
      year: 2024,
      city: "Pune",
      hubId: "pune-symbiosis",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 4,
      pricePerHour: 225,
      pricePerDay: 3199,
      rating: 4.95,
      tripsCount: 290,
      image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
      features: ["4x4 Low Range", "Convertible", "Rugged Offroad", "FASTag"],
      location: "Viman Nagar Phoenix Mall • 0.6 km away",
      zeroDeposit: true,
      badge: "Ghats Special ⛰️",
      quickBubble: "⛰️ 4x4 Offroad • Lavasa & Mahabaleshwar Ready",
      specs: { mileage: "14.0 km/l", boot: "Adventure Space", speed: "155 km/h", sound: "Adventure Audio" },
      desc: "Conquer Mahabaleshwar hairpin bends and Lavasa mountain roads in style."
    },
    {
      id: "car-scorpio-pune",
      name: "Mahindra Scorpio-N (7 Seater)",
      year: 2024,
      city: "Pune",
      hubId: "pune-fc",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 7,
      pricePerHour: 250,
      pricePerDay: 3599,
      rating: 4.93,
      tripsCount: 270,
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      features: ["7 Full-size Seats", "Turbo Petrol AT", "Sony 3D Audio", "Dual Zone AC"],
      location: "MIT Kothrud Main Gate • 0.5 km away",
      zeroDeposit: true,
      badge: "Big Squad 7-Seater 👥",
      quickBubble: "👥 7 Seats • Automatic • Sony 3D Sound",
      specs: { mileage: "13.8 km/l", boot: "Modular Boot", speed: "175 km/h", sound: "Sony 3D Surround" },
      desc: "Perfect for taking the whole hostel squad down to Goa on the new expressway."
    },

    // ---------------- MUMBAI ----------------
    {
      id: "car-nexon-ev",
      name: "Tata Nexon EV Max",
      year: 2024,
      city: "Mumbai",
      hubId: "mum-powai",
      category: "ev",
      categoryName: "Electric EV",
      transmission: "Automatic",
      fuel: "Electric",
      seats: 5,
      pricePerHour: 140,
      pricePerDay: 1999,
      rating: 4.89,
      tripsCount: 210,
      image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
      features: ["453 km Range", "Fast Charging 0-80% in 50m", "Zero Fuel Expense", "Silent Cabin & Instant Torque"],
      location: "Powai IIT Gate • 0.5 km away",
      zeroDeposit: true,
      badge: "Zero Fuel Cost 🔋",
      quickBubble: "🔋 453km Electric Range • ₹0 Fuel • Instant Torque",
      specs: { mileage: "453 km / Full Charge", boot: "350 Litres", speed: "140 km/h", sound: "Harman 8-Speaker Studio" },
      desc: "Save 100% on petrol! Cruise silently with electric torque and complimentary fast charging at 5,000+ public charging stations."
    },
    {
      id: "car-bmw",
      name: "BMW 330i M-Sport",
      year: 2023,
      city: "Mumbai",
      hubId: "mum-bandra",
      category: "luxury",
      categoryName: "Flex / Luxury",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 450,
      pricePerDay: 6499,
      rating: 4.98,
      tripsCount: 165,
      image: "https://images.unsplash.com/photo-1555353540-64580b51c258?auto=format&fit=crop&w=800&q=80",
      features: ["258 BHP Twin-Turbo", "Harman Kardon Surround", "M-Sport Body Styling", "Heads-Up Display"],
      location: "Bandra West Promenade • 2.0 km away",
      zeroDeposit: false,
      badge: "Graduation Flex 👑",
      quickBubble: "👑 258 BHP Twin-Turbo • Harman Kardon • M-Sport",
      specs: { mileage: "13.8 km/l", boot: "480 Litres", speed: "250 km/h (Track Tested)", sound: "Harman Kardon 16-Speaker" },
      desc: "Turn every head on campus. The ultimate luxury flex for college fest arrivals, graduation galas, birthday night outs, and premium dates."
    },
    {
      id: "car-creta-mum",
      name: "Hyundai Creta Turbo Petrol",
      year: 2024,
      city: "Mumbai",
      hubId: "mum-bandra",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 210,
      pricePerDay: 2999,
      rating: 4.92,
      tripsCount: 380,
      image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
      features: ["Panoramic Sunroof", "Paddle Shifters", "Bose Audio", "Ventilated Seats"],
      location: "Mithibai College Gate • 0.3 km away",
      zeroDeposit: true,
      badge: "Marine Drive Cruise 🌊",
      quickBubble: "🌊 Panoramic Sunroof • Turbo AT • Bandra Hub",
      specs: { mileage: "17.0 km/l", boot: "433 Litres", speed: "185 km/h", sound: "Bose 8-Speaker" },
      desc: "Breeze along Marine Drive and Sea Link with the panoramic sunroof wide open."
    },
    {
      id: "car-swift-mum",
      name: "Maruti Suzuki Swift",
      year: 2024,
      city: "Mumbai",
      hubId: "mum-bandra",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Manual",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 105,
      pricePerDay: 1449,
      rating: 4.87,
      tripsCount: 410,
      image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
      features: ["Apple CarPlay", "FASTag Enabled", "Super Mileage", "Touchscreen"],
      location: "NMIMS Vile Parle • 0.4 km away",
      zeroDeposit: true,
      badge: "City Runner ⚡",
      quickBubble: "⚡ ₹1,449/day • Easy Parking • Great Mileage",
      specs: { mileage: "22.5 km/l", boot: "268 Litres", speed: "165 km/h", sound: "6-Speaker Audio" },
      desc: "Nimble city runner that slips into tiny Mumbai parking slots with zero effort."
    },

    // ---------------- CHENNAI / VELLORE ----------------
    {
      id: "car-swift-chn",
      name: "Maruti Suzuki Swift",
      year: 2024,
      city: "Chennai / Vellore",
      hubId: "chn-vit",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Manual",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 95,
      pricePerDay: 1349,
      rating: 4.88,
      tripsCount: 320,
      image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
      features: ["Bluetooth", "Fastag", "Chill AC", "Super Mileage"],
      location: "VIT Chennai Campus Gate 1 • 0.3 km away",
      zeroDeposit: true,
      badge: "Pondy Roadtrip 🏖️",
      quickBubble: "🏖️ Pondy Run Special • 22 km/l • ECR Ready",
      specs: { mileage: "22.5 km/l", boot: "268 Litres", speed: "165 km/h", sound: "6-Speaker Stereo" },
      desc: "Top pick for East Coast Road runs to Pondicherry. Cheap fuel spend and breezy coastal cruising."
    },
    {
      id: "car-virtus-chn",
      name: "Volkswagen Virtus GT",
      year: 2024,
      city: "Chennai / Vellore",
      hubId: "chn-vit",
      category: "sedan",
      categoryName: "Vibe Sedan",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 175,
      pricePerDay: 2499,
      rating: 4.93,
      tripsCount: 210,
      image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
      features: ["German Safety", "150 BHP Turbo", "Paddle Shifters", "Huge Boot"],
      location: "OMR Tech Corridor Hub • 0.7 km away",
      zeroDeposit: true,
      badge: "ECR Highway Vibe 🏎️",
      quickBubble: "🏎️ 150 BHP Turbo • 5-Star NCAP • Digital Cockpit",
      specs: { mileage: "18.1 km/l", boot: "521 Litres", speed: "205 km/h", sound: "Digital Cockpit Audio" },
      desc: "High-speed coastal stability along the Bay of Bengal coastline."
    },
    {
      id: "car-scorpio-chn",
      name: "Mahindra Scorpio-N (7 Seater)",
      year: 2024,
      city: "Chennai / Vellore",
      hubId: "chn-vit",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 7,
      pricePerHour: 235,
      pricePerDay: 3399,
      rating: 4.94,
      tripsCount: 290,
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      features: ["7 Full-size Seats", "mHawk Diesel", "Sony 3D Sound", "Dual AC"],
      location: "VIT Main Gate • 0.5 km away",
      zeroDeposit: true,
      badge: "Big Squad 7-Seater 👥",
      quickBubble: "👥 7 Seats • mHawk Diesel • Sony Sound",
      specs: { mileage: "15.0 km/l", boot: "Modular Boot", speed: "175 km/h", sound: "Sony 3D Sound" },
      desc: "Pack your entire room or society wing for a Mahabalipuram surf trip."
    },
    {
      id: "car-verna-chn",
      name: "Hyundai Verna Diesel",
      year: 2023,
      city: "Chennai / Vellore",
      hubId: "chn-vit",
      category: "sedan",
      categoryName: "Vibe Sedan",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 5,
      pricePerHour: 165,
      pricePerDay: 2399,
      rating: 4.86,
      tripsCount: 180,
      image: "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
      features: ["High Torque Diesel", "Bose Audio", "Chilled Seats", "Fastag"],
      location: "OMR Sholinganallur • 0.9 km away",
      zeroDeposit: true,
      badge: "Diesel Cruiser ⛽",
      quickBubble: "⛽ 24 km/l • Chilled Seats • Long Range",
      specs: { mileage: "24.2 km/l", boot: "528 Litres", speed: "195 km/h", sound: "Bose Surround" },
      desc: "Long highway runs with outstanding diesel economy across Tamil Nadu."
    },

    // ---------------- MANIPAL ----------------
    {
      id: "car-thar-mnp",
      name: "Mahindra Thar 4x4",
      year: 2024,
      city: "Manipal",
      hubId: "manipal",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 4,
      pricePerHour: 220,
      pricePerDay: 3199,
      rating: 4.96,
      tripsCount: 410,
      image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
      features: ["4x4 Low Range", "Convertible Top", "Touchscreen", "FASTag"],
      location: "MIT Manipal Tiger Circle • 0.2 km away",
      zeroDeposit: true,
      badge: "Malpe Beach Special 🏖️",
      quickBubble: "🏖️ Malpe & Kudremukh Ready • 4x4 Power",
      specs: { mileage: "14.2 km/l", boot: "Adventure Space", speed: "155 km/h", sound: "Adventure Audio" },
      desc: "The heartbeat of Manipal road trips. Drive down to Malpe beach, Delta point, and Western Ghats waterfalls."
    },
    {
      id: "car-swift-mnp",
      name: "Maruti Suzuki Swift",
      year: 2024,
      city: "Manipal",
      hubId: "manipal",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Manual",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 99,
      pricePerDay: 1399,
      rating: 4.85,
      tripsCount: 390,
      image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
      features: ["Apple CarPlay", "Fastag", "22 km/l Mileage", "Bluetooth"],
      location: "Tiger Circle Manipal • 0.3 km away",
      zeroDeposit: true,
      badge: "Student Saver 💸",
      quickBubble: "💸 ₹1,399/day • Easy Student Booking",
      specs: { mileage: "22.5 km/l", boot: "268 Litres", speed: "165 km/h", sound: "Stereo System" },
      desc: "Pocket-friendly rides for late-night food runs to Udupi and beach sunsets."
    },
    {
      id: "car-creta-mnp",
      name: "Hyundai Creta SX Turbo",
      year: 2024,
      city: "Manipal",
      hubId: "manipal",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 195,
      pricePerDay: 2799,
      rating: 4.91,
      tripsCount: 230,
      image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
      features: ["Panoramic Sunroof", "Paddle Shifters", "Bose Audio", "Cruise Control"],
      location: "KMC Green Area Manipal • 0.4 km away",
      zeroDeposit: true,
      badge: "Sunroof Vibe ✨",
      quickBubble: "✨ Panoramic Sunroof • Turbo Automatic",
      specs: { mileage: "17.2 km/l", boot: "433 Litres", speed: "185 km/h", sound: "Bose 8-Speaker" },
      desc: "Spacious and luxurious for weekend getaways to Gokarna and Coorg."
    },

    // ---------------- GOA ----------------
    {
      id: "car-thar-goa",
      name: "Mahindra Thar 4x4 Convertible",
      year: 2024,
      city: "Goa",
      hubId: "goa-bits",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 4,
      pricePerHour: 250,
      pricePerDay: 3599,
      rating: 4.98,
      tripsCount: 520,
      image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
      features: ["Open Top Convertible", "Automatic 4x4", "Bluetooth Party Audio", "FASTag"],
      location: "BITS Pilani Goa Gate • 0.3 km away",
      zeroDeposit: true,
      badge: "Beach Vibe Icon 🌴",
      quickBubble: "🌴 Open-Air Convertible • Automatic • BITS Goa Hub",
      specs: { mileage: "13.2 km/l", boot: "Beach Gear Space", speed: "155 km/h", sound: "Roof Soundstage" },
      desc: "The ultimate Goa fantasy. Drive down Anjuna, Vagator, and Palolem with the roof down and sea breeze blowing."
    },
    {
      id: "car-creta-goa",
      name: "Hyundai Creta Sunroof",
      year: 2024,
      city: "Goa",
      hubId: "goa-bits",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Diesel",
      seats: 5,
      pricePerHour: 210,
      pricePerDay: 2999,
      rating: 4.92,
      tripsCount: 430,
      image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
      features: ["Panoramic Sunroof", "Chilled AC", "Bose Audio", "433L Boot"],
      location: "Panjim Coastal Promenade • 1.0 km away",
      zeroDeposit: true,
      badge: "Sunroof Cruiser ✨",
      quickBubble: "✨ Panoramic Sunroof • Diesel Automatic",
      specs: { mileage: "18.5 km/l", boot: "433 Litres", speed: "180 km/h", sound: "Bose Surround" },
      desc: "Comfortable air-conditioned luxury for exploring North and South Goa beaches."
    },
    {
      id: "car-swift-goa",
      name: "Maruti Suzuki Swift",
      year: 2024,
      city: "Goa",
      hubId: "goa-bits",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Manual",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 105,
      pricePerDay: 1499,
      rating: 4.87,
      tripsCount: 460,
      image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
      features: ["Apple CarPlay", "22 km/l Mileage", "FASTag", "Touchscreen"],
      location: "BITS Goa Campus Gate • 0.4 km away",
      zeroDeposit: true,
      badge: "Budget Explorer 💸",
      quickBubble: "💸 ₹1,499/day • Super Low Fuel Spend",
      specs: { mileage: "22.5 km/l", boot: "268 Litres", speed: "165 km/h", sound: "Stereo Sound" },
      desc: "Affordable Goa exploring for student budgets. Fits in narrow village lanes with ease."
    },
    {
      id: "car-bmw-goa",
      name: "BMW 330i M-Sport",
      year: 2023,
      city: "Goa",
      hubId: "goa-bits",
      category: "luxury",
      categoryName: "Flex / Luxury",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 480,
      pricePerDay: 6999,
      rating: 4.99,
      tripsCount: 140,
      image: "https://images.unsplash.com/photo-1555353540-64580b51c258?auto=format&fit=crop&w=800&q=80",
      features: ["258 BHP Twin-Turbo", "Harman Kardon", "M-Sport Package", "Sunroof"],
      location: "Panjim Luxury Hub • 1.5 km away",
      zeroDeposit: false,
      badge: "VIP Club Flex 👑",
      quickBubble: "👑 258 BHP • Harman Kardon • Beach Club Entry",
      specs: { mileage: "13.5 km/l", boot: "480 Litres", speed: "250 km/h", sound: "Harman Kardon 16-Speaker" },
      desc: "Roll up to Thalassa, HillTop, and luxury beach clubs with unmatched VIP swagger."
    },
    {
      id: "car-scorpio-goa",
      name: "Mahindra Scorpio-N (7 Seater)",
      year: 2024,
      city: "Goa",
      hubId: "goa-bits",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 7,
      pricePerHour: 260,
      pricePerDay: 3799,
      rating: 4.95,
      tripsCount: 380,
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      features: ["7 Full-size Seats", "Sony 3D Sound", "High Clearance", "Powerful Diesel"],
      location: "BITS Goa Main Circle • 0.5 km away",
      zeroDeposit: true,
      badge: "Big Squad 7-Seater 👥",
      quickBubble: "👥 7 Seats • Sony 3D Sound • Beach Squad",
      specs: { mileage: "14.8 km/l", boot: "Modular Boot", speed: "175 km/h", sound: "Sony 3D Surround" },
      desc: "The ultimate road trip machine for 7 friends traveling together in Goa."
    },

    // ---------------- HYDERABAD ----------------
    {
      id: "car-virtus-hyd",
      name: "Volkswagen Virtus GT",
      year: 2024,
      city: "Hyderabad",
      hubId: "hyd-gachibowli",
      category: "sedan",
      categoryName: "Vibe Sedan",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 180,
      pricePerDay: 2599,
      rating: 4.92,
      tripsCount: 310,
      image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
      features: ["150 BHP Turbo", "Digital Cockpit", "Paddle Shifters", "ORR Ready"],
      location: "IIIT Hyderabad Main Gate • 0.3 km away",
      zeroDeposit: true,
      badge: "ORR Speedster 🏎️",
      quickBubble: "🏎️ 150 BHP Turbo • Outer Ring Road Cruiser",
      specs: { mileage: "18.1 km/l", boot: "521 Litres", speed: "205 km/h", sound: "Digital Cockpit Audio" },
      desc: "Fly across the Hyderabad Outer Ring Road (ORR) with 150 BHP German turbo power."
    },
    {
      id: "car-swift-hyd",
      name: "Maruti Suzuki Swift",
      year: 2024,
      city: "Hyderabad",
      hubId: "hyd-gachibowli",
      category: "pocket",
      categoryName: "Pocket Saver",
      transmission: "Manual",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 99,
      pricePerDay: 1399,
      rating: 4.86,
      tripsCount: 370,
      image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=800&q=80",
      features: ["Apple CarPlay", "22 km/l Mileage", "FASTag", "Bluetooth"],
      location: "Gachibowli Stadium Hub • 0.6 km away",
      zeroDeposit: true,
      badge: "Biryani Night Runner ⚡",
      quickBubble: "⚡ ₹1,399/day • Midnight Biryani Special",
      specs: { mileage: "22.5 km/l", boot: "268 Litres", speed: "165 km/h", sound: "6-Speaker Audio" },
      desc: "Midnight drives to Charminar and late-night biryani spots made pocket-friendly."
    },
    {
      id: "car-creta-hyd",
      name: "Hyundai Creta SX Turbo",
      year: 2024,
      city: "Hyderabad",
      hubId: "hyd-gachibowli",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Automatic",
      fuel: "Petrol",
      seats: 5,
      pricePerHour: 205,
      pricePerDay: 2849,
      rating: 4.93,
      tripsCount: 280,
      image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
      features: ["Panoramic Sunroof", "Bose Audio", "Ventilated Seats", "Cruise Control"],
      location: "HITEC City Cyber Towers • 0.8 km away",
      zeroDeposit: true,
      badge: "Sunroof Turbo ✨",
      quickBubble: "✨ Panoramic Sunroof • Turbo Automatic",
      specs: { mileage: "17.0 km/l", boot: "433 Litres", speed: "185 km/h", sound: "Bose Surround" },
      desc: "Smooth turbo-petrol SUV with a panoramic sunroof for Ananthagiri Hills getaways."
    },
    {
      id: "car-scorpio-hyd",
      name: "Mahindra Scorpio-N (7 Seater)",
      year: 2024,
      city: "Hyderabad",
      hubId: "hyd-gachibowli",
      category: "suv",
      categoryName: "Squad SUV",
      transmission: "Manual",
      fuel: "Diesel",
      seats: 7,
      pricePerHour: 245,
      pricePerDay: 3549,
      rating: 4.94,
      tripsCount: 310,
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      features: ["7 Full-size Seats", "mHawk Diesel", "Sony 3D Sound", "Dual Zone AC"],
      location: "Gachibowli DLF Street • 0.4 km away",
      zeroDeposit: true,
      badge: "Big Squad 7-Seater 👥",
      quickBubble: "👥 7 Seats • 175 BHP Diesel • Sony 3D",
      specs: { mileage: "14.9 km/l", boot: "Modular Boot", speed: "175 km/h", sound: "Sony 3D Surround" },
      desc: "Room for 7 friends to head to Srisailam dam and Nagarjuna Sagar on weekends."
    },
    {
      id: "car-nexon-hyd",
      name: "Tata Nexon EV Max",
      year: 2024,
      city: "Hyderabad",
      hubId: "hyd-gachibowli",
      category: "ev",
      categoryName: "Electric EV",
      transmission: "Automatic",
      fuel: "Electric",
      seats: 5,
      pricePerHour: 140,
      pricePerDay: 1999,
      rating: 4.88,
      tripsCount: 195,
      image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80",
      features: ["453 km Range", "₹0 Fuel Expense", "Fast Charging", "Harman Audio"],
      location: "IIIT Hyderabad Gate 2 • 0.3 km away",
      zeroDeposit: true,
      badge: "Zero Fuel Cost 🔋",
      quickBubble: "🔋 453km Electric Range • ₹0 Fuel",
      specs: { mileage: "453 km / Full Charge", boot: "350 Litres", speed: "140 km/h", sound: "Harman 8-Speaker" },
      desc: "Save every rupee on petrol while enjoying instant electric torque on the expressway."
    }
  ],

  roadTrips: [
    {
      title: "Bangalore ➔ Nandi Hills & Coorg",
      from: "Bangalore",
      distance: "245 km",
      time: "4.5 hrs",
      tag: "COFFEE & CLOUDS",
      recommendedCar: "Mahindra Thar 4x4",
      image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?auto=format&fit=crop&w=600&q=80",
      vibe: "Early morning fog, chai stops, lush greenery & winding forest roads."
    },
    {
      title: "Delhi ➔ Murthal Dhabas & Rishikesh",
      from: "Delhi NCR",
      distance: "230 km",
      time: "4.0 hrs",
      tag: "MIDNIGHT PARATHAS & RAFTING",
      recommendedCar: "Tata Nexon / Swift",
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=600&q=80",
      vibe: "Garma-garam parathas with white makkhan at 2 AM followed by Ganga river rafting."
    },
    {
      title: "Mumbai / Pune ➔ Lonavala & Goa",
      from: "Mumbai / Pune",
      distance: "480 km",
      time: "8.5 hrs",
      tag: "BEACH & SUNSET VIBES",
      recommendedCar: "Hyundai Creta Sunroof",
      image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=600&q=80",
      vibe: "Expressway cruising, waterfall viewpoints, beach shacks, and epic hostel after-parties."
    },
    {
      title: "Chennai ➔ Pondicherry ECR Coastal Run",
      from: "Chennai",
      distance: "150 km",
      time: "2.5 hrs",
      tag: "COASTAL BREEZE",
      recommendedCar: "VW Virtus GT",
      image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
      vibe: "Ocean breeze on East Coast Road, French bakeries, surfing cafes & sunrise drives."
    }
  ],

  studentReviews: [
    {
      name: "Aarav Sharma",
      college: "IIT Bombay (Powai)",
      avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80",
      car: "Mahindra Thar 4x4",
      trip: "Goa Semester Break",
      rating: 5,
      comment: "Split the Thar with 4 hostel wingmates — it came down to just ₹750 each per day! Bluetooth connected instantly and zero deposit with my student ID. Unbeatable experience."
    },
    {
      name: "Sneha Nair",
      college: "Christ University (Koramangala)",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
      car: "Maruti Swift 2024",
      trip: "Nandi Hills Sunrise Run",
      rating: 5,
      comment: "Booked the Midnight Pack at 2 AM for a quick Nandi Hills sunrise trip. Car was dropped right outside our PG gate in 20 minutes with keyless unlock. 10/10 recommend CRUIZR!"
    },
    {
      name: "Rohan Kapoor",
      college: "SRCC, Delhi University",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
      car: "Tata Nexon EV",
      trip: "Rishikesh Weekend",
      rating: 5,
      comment: "Used code STUDENT25 for an insane 25% discount. Electric range was super solid and we literally spent ₹0 on petrol because charging was free on highway hubs."
    },
    {
      name: "Tanya Deshmukh",
      college: "Symbiosis Law School, Pune",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
      car: "Hyundai Creta Sunroof",
      trip: "Mahabaleshwar Roadtrip",
      rating: 5,
      comment: "The built-in split fare tool in the app made collecting money from friends so easy. No awkward payment followups. Sunroof open on the ghats was pure vibes."
    }
  ],

  faqs: [
    {
      q: "Can I rent a car with a college ID and fresh driving license?",
      a: "Yes! As long as you have a valid permanent driving license (even if issued recently) and a government ID or College Student ID / .edu email, you are eligible to drive all standard cars on CRUIZR with ZERO security deposit."
    },
    {
      q: "How does the 'Split Fare with Friends' feature work?",
      a: "When you select any car, our live Split-Fare slider lets you choose your friend count (1 to 7 people). It instantly divides the total rent, fuel, and toll costs equally so you know your exact per-person share."
    },
    {
      q: "Is doorstep delivery available directly to my hostel or PG?",
      a: "Absolutely! Toggle 'Hostel / Doorstep Delivery' during booking, enter your campus gate or hostel location, and a verified CRUIZR host or fleet executive will drop the sanitized car right at your doorstep."
    },
    {
      q: "What is the Midnight / Night Drive Pack?",
      a: "Night Drive Pack is tailored for college food runs, late night drives, and sunrise trips (8:00 PM to 6:00 AM). You get flat special pricing starting at just ₹499 with code NIGHTOWL."
    },
    {
      q: "How do I unlock the car without physical keys?",
      a: "All CRUIZR cars are equipped with Smart IoT keyless entry. Once your booking starts, simply tap 'Unlock Car' on your phone to unlock the doors and start driving."
    },
    {
      q: "Are toll gate passes (FASTag) and Aux/Bluetooth included?",
      a: "Yes! 100% of our fleet comes with an active FASTag so you never wait in toll queues. Plus, every car is verified to have working Bluetooth / Apple CarPlay / Android Auto so your road trip playlist never stops."
    }
  ]
};
